name: CI/CD for BankProject

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-build-deploy:
    name: Lint, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use the required Node.js version
          cache: 'npm'

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Lint the code
      - name: Lint Code
        run: npm run lint

      # Build the project
      - name: Build Project
        run: npm run build

      # Deploy to GitHub Pages or another platform (example: Firebase Hosting)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist # Vite's build output directory