name: CI/CD for BankProject

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Lint Application
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Source
      - name: Checkout Source
        uses: actions/checkout@v3

      # Step 2: Setup Node.js Environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install --unsafe-perm

      # Step 4: Fix ESLint Permissions
      - name: Fix ESLint Permissions
        run: chmod +x ./node_modules/.bin/eslint

      # Step 5: Lint the Code
      - name: Lint Code
        run: npx eslint . # Use npx to ensure the local version is used

      # Step 6: Build the Project
      - name: Build Application
        run: npm run build

      # Step 7: Publish Docker Image to Docker Hub
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t bankproject/frontend:latest .
      - name: Push Docker Image
        run: docker push bankproject/frontend:latest

  deploy:
    name: Deploy Frontend Application
    runs-on: self-hosted
    needs: build
    steps:
      # Step 1: Pull Image from Docker Hub
      - name: Pull Image from Docker Hub
        run: docker pull bankproject/frontend:latest

      # Step 2: Run Docker Container
      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name bankproject-frontend bankproject/frontend:latest